### PR TITLE
Add build folder to gitignore

### PR DESCRIPTION
**Pull request by JulianGro**

### CODE REVIEW

**Comment by IF-Adin** [comment]
Why? It's not taking a lot of room and is useful to people to see the build files.

**Comment by JulianGro** [comment]
Oh, It's just annoying to have it show up constantly all over git. You also cannot view the build website comfortably with this; You still need to clone the repo to actually view it.
Well and if you want to see the website you can just navigate to a live version of it.

**Comment by IF-Adin** [comment]
Well this has to be more selective, we need the build files for the deployment.

**Comment by JulianGro** [comment]
Yes, normally you either build it and upload it yourself, or you have something like #3 do that.

**Comment by IF-Adin** [comment]
Yes, but why bother letting the ci/cd build it? Hm, i'll think about it. The files don't bother me that much personally.

**Pull request merged**
